# Generated by Django 3.1.2 on 2020-10-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
