# Generated by Django 3.1.2 on 2020-10-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storeunion',
            fields=[
                ('storeid', models.AutoField(db_column='storeId', primary_key=True, serialize=False)),
                ('storename', models.CharField(db_column='storeName', max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('phonenum', models.IntegerField(db_column='phoneNum')),
                ('email', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'storeunion',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=40)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('isadmin', models.TextField(db_column='isAdmin')),
                ('phonenum', models.IntegerField(db_column='phoneNum')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetid', models.AutoField(db_column='budgetId', primary_key=True, serialize=False)),
                ('totalbills', models.DecimalField(db_column='totalBills', decimal_places=2, max_digits=10)),
                ('moneyleft', models.DecimalField(db_column='moneyLeft', decimal_places=2, max_digits=10)),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='bills.users')),
            ],
            options={
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('billid', models.AutoField(db_column='billId', primary_key=True, serialize=False)),
                ('billname', models.CharField(db_column='billName', max_length=50)),
                ('billdate', models.DateField(db_column='BillDate')),
                ('billprice', models.DecimalField(db_column='billPrice', decimal_places=2, max_digits=5)),
                ('islate', models.TextField(db_column='isLate')),
                ('budgetid', models.ForeignKey(db_column='budgetId', on_delete=django.db.models.deletion.DO_NOTHING, to='bills.budget')),
                ('storeid', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.DO_NOTHING, to='bills.storeunion')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
