# Generated by Django 3.1.2 on 2020-10-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20201025_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
