# Generated by Django 3.1.2 on 2020-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20201026_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(db_column='password', max_length=128),
        ),
    ]
