# Generated by Django 3.1.2 on 2020-11-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20201104_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeunion',
            name='is_credit_union',
            field=models.BooleanField(db_column='isCreditUnion', default=False),
        ),
    ]
