# Generated by Django 3.1.2 on 2020-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_storeunion_is_credit_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeunion',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storeunion',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
