# Generated by Django 3.1.2 on 2020-11-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_remove_bills_islate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='end_date',
            field=models.DateField(db_column='endDate', default='2020-11-6'),
        ),
        migrations.AddField(
            model_name='bills',
            name='islate',
            field=models.TextField(db_column='isLate', default=False),
        ),
    ]
