# Generated by Django 3.1.2 on 2020-11-07 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_auto_20201104_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('miscid', models.AutoField(db_column='miscId', primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField()),
                ('storeid', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.DO_NOTHING, to='bills.storeunion')),
                ('userid', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'misc',
            },
        ),
    ]
