# Generated by Django 3.1.2 on 2020-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_auto_20201107_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='misc_name',
            field=models.CharField(db_column='miscName', default='Groceries', max_length=100),
        ),
    ]
