# Generated by Django 3.1.2 on 2020-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_auto_20201113_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeunion',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
