# Generated by Django 3.1.2 on 2020-11-14 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_auto_20201113_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subid', models.AutoField(db_column='subId', primary_key=True, serialize=False)),
                ('duedate', models.DateField(db_column='dueDate')),
                ('amountdue', models.DecimalField(blank=True, db_column='amountDue', decimal_places=2, max_digits=6, null=True)),
                ('subname', models.CharField(blank=True, db_column='subName', max_length=50, null=True)),
                ('storeid', models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.DO_NOTHING, to='bills.storeunion')),
                ('userid', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
