# Generated by Django 3.1.2 on 2020-11-15 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='budgetid',
        ),
        migrations.AddField(
            model_name='bills',
            name='user_id',
            field=models.ForeignKey(db_column='userId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bills.users'),
            preserve_default=False,
        ),
    ]
