# Generated by Django 3.1.2 on 2020-11-15 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_auto_20201114_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='user_id',
            field=models.ForeignKey(db_column='userId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanid', models.AutoField(db_column='loanId', primary_key=True, serialize=False)),
                ('loanname', models.CharField(db_column='loanName', max_length=50)),
                ('duedate', models.DateField(db_column='dueDate')),
                ('monthlyamountdue', models.DecimalField(blank=True, db_column='monthlyAmountDue', decimal_places=2, max_digits=6, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalamountdue', models.DecimalField(blank=True, db_column='totalAmountDue', decimal_places=2, max_digits=6, null=True)),
                ('storeid', models.ForeignKey(db_column='storeId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bills.storeunion')),
                ('userid', models.ForeignKey(db_column='userId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
