# Generated by Django 3.1.2 on 2020-11-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_auto_20201114_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='end_date',
        ),
    ]
