# Generated by Django 3.1.2 on 2020-11-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0024_auto_20201115_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='billdate',
            field=models.DateField(db_column='billDate'),
        ),
    ]
