# Generated by Django 3.1.2 on 2020-11-24 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(db_column='replyId', primary_key=True, serialize=False)),
                ('reply_body', models.CharField(db_column='replyBody', max_length=200)),
                ('date', models.DateField()),
                ('post_id', models.ForeignKey(db_column='postId', on_delete=django.db.models.deletion.CASCADE, to='community.post')),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reply',
            },
        ),
    ]
