# Generated by Django 3.1.2 on 2020-11-30 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(db_column='commentId', primary_key=True, serialize=False)),
                ('comment_body', models.CharField(db_column='commentBody', max_length=200)),
                ('date', models.DateTimeField()),
                ('post_id', models.ForeignKey(db_column='postId', on_delete=django.db.models.deletion.CASCADE, to='community.post')),
                ('user_id', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AlterField(
            model_name='reply',
            name='post_id',
            field=models.ForeignKey(db_column='commentId', on_delete=django.db.models.deletion.CASCADE, to='community.comments'),
        ),
    ]
