# Generated by Django 3.1.2 on 2020-11-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20201130_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post_id',
            new_name='comment_id',
        ),
    ]
