# Generated by Django 3.1.2 on 2020-11-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(db_column='endDate', default='2020-11-30'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(db_column='startDate', default='2020-11-30'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desciption',
            field=models.TextField(null=True),
        ),
    ]
